<a href="https://colab.research.google.com/github/cirojunior/stateofdatabrazil2023/blob/main/portifolio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Os dados vão ser coletados e importados do kaggle do link abaixo

https://www.kaggle.com/datasets/datahackers/state-of-data-brazil-2023/data

In [1]:
import kagglehub
import os
import shutil
import pandas as pd

In [2]:
# Download latest version
path = kagglehub.dataset_download("datahackers/state-of-data-brazil-2023")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/datahackers/state-of-data-brazil-2023?dataset_version_number=1...

100%|██████████| 1.58M/1.58M [00:00<00:00, 22.2MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/datahackers/state-of-data-brazil-2023/versions/1

In [3]:
# Verificar quais arquivos estão dentro do diretório
print("Arquivos disponíveis:")
print(os.listdir(path))

Arquivos disponíveis:
['State_of_data_BR_2023_Kaggle - df_survey_2023.csv']

In [4]:
# Origem: onde está o arquivo
arquivo_origem = os.path.join(path, "State_of_data_BR_2023_Kaggle - df_survey_2023.csv")

# Destino: sua estrutura de projeto
arquivo_destino = "/content/sample_data/State_of_data_BR_2023_Kaggle - df_survey_2023.csv"

shutil.copyfile(arquivo_origem, arquivo_destino)

'/content/sample_data/State_of_data_BR_2023_Kaggle - df_survey_2023.csv'

In [5]:
#Garantindo que estou na pasta do projeto.
os.chdir("/content/sample_data")

In [6]:
#Verificando se esta na pasta correta.
os.getcwd()

'/content/sample_data'

In [7]:
#Carregando o arquivo para dentro do DataFrame usando o pandas
df = pd.read_csv('State_of_data_BR_2023_Kaggle - df_survey_2023.csv')

In [8]:
df.head(5)

,"('P0', 'id')","('P1_a ', 'Idade')","('P1_a_1 ', 'Faixa idade')","('P1_b ', 'Genero')","('P1_c ', 'Cor/raca/etnia')","('P1_d ', 'PCD')","('P1_e ', 'experiencia_profissional_prejudicada')","('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada')","('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia')","('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero')",...,"('P8_d_3 ', 'Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.')","('P8_d_4 ', 'Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).')","('P8_d_5 ', 'Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.')","('P8_d_6 ', 'Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.')","('P8_d_7 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.')","('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')","('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')","('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')","('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')","('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')"
0,001b2d1qtli8t9z7oqgdhj001b2d4i0g,31,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0026aa3fwd78u0026asg7456tfkjg2cs,30,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00r21rb9pusd1b0v7ew00r21rw3dy69w,37,35-39,Feminino,Amarela,Não,"Sim, acredito que a minha a experiência profis...",0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00urm3jf2cek12w6ygue00urm3jzd17j,22,22-24,Masculino,Preta,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00v0az4g792svil00vn6y1kfm9hq8vy9,34,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.columns

Index(['('P0', 'id')', '('P1_a ', 'Idade')', '('P1_a_1 ', 'Faixa idade')',
       '('P1_b ', 'Genero')', '('P1_c ', 'Cor/raca/etnia')',
       '('P1_d ', 'PCD')', '('P1_e ', 'experiencia_profissional_prejudicada')',
       '('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada')',
       '('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia')',
       '('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero')',
       ...
       '('P8_d_3 ', 'Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.')',
       '('P8_d_4 ', 'Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).')',
       '('P8_d_5 ', 'Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.')',
       '('P8_d_6 ', 'Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.')',
       '('P8_d_7 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.')',
       '('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')',
       '('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')',
       '('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')',
       '('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')',
       '('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')'],
      dtype='object', length=399)

In [11]:
df.describe()

,"('P1_a ', 'Idade')","('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada')","('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia')","('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero')","('P1_e_4 ', 'Experiencia prejudicada devido ao fato de ser PCD')","('P1_f_1', 'Quantidade de oportunidades de emprego/vagas recebidas')","('P1_f_2', 'Senioridade das vagas recebidas em relação à sua experiência')","('P1_f_3', 'Aprovação em processos seletivos/entrevistas')","('P1_f_4', 'Oportunidades de progressão de carreira')","('P1_f_5', 'Velocidade de progressão de carreira')",...,"('P8_d_3 ', 'Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.')","('P8_d_4 ', 'Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).')","('P8_d_5 ', 'Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.')","('P8_d_6 ', 'Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.')","('P8_d_7 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.')","('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')","('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')","('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')","('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')","('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')"
count,5293.000000,2719.000000,2719.000000,2719.000000,2719.000000,1245.000000,1245.000000,1245.000000,1245.000000,1245.000000,...,748.000000,748.000000,748.000000,748.000000,748.000000,748.000000,748.000000,748.000000,748.000000,748.000000
mean,31.997166,0.542111,0.202648,0.291284,0.024641,0.389558,0.342972,0.413655,0.490763,0.516466,...,0.243316,0.315508,0.070856,0.093583,0.045455,0.009358,0.025401,0.020053,0.024064,0.048128
std,7.623498,0.498315,0.402046,0.454437,0.155058,0.487846,0.474893,0.492686,0.500116,0.499930,...,0.429371,0.465029,0.256755,0.291442,0.208438,0.096349,0.157445,0.140277,0.153351,0.214181
min,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,30.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,36.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,73.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

**Tratando o nome das colunas do DataFrame para ficar melhor o uso.**


Crio uma função para reaproveitar código e dentro dele coloco um for para passar por todas as colunas que existem no DataFrame e na sequencia uso um Try para garantir que erros não vão deixar o código parar, dentro do Try faço os replace "Substituição de caracteres" e o split "Para separar os textos por um separador e transformar em lista".


Utilizo do rename para renomear as colunas do DataFrame onde passo a variável do for como o nome original da coluna e a variável que contem o texto formatado.


Uso excep pass para seguir o código caos encontre um problema, uma vez alterado o nome da coluna se rodar o codigo novamente vai dar erro porque não vai encontrar o nome original que veio dos dados.

In [78]:
def replaceColumns(coluna):
  for i in coluna:
    try:
      c = i.replace("('","")
      c = c.replace("')","")
      c = c.replace("', '",",")
      c = c.replace(" ,",",")
      c = c.split(",")
      df.rename(columns={i:c[1]}, inplace=True)
    except:
      pass
    #df.rename(columns={i:c[1]}, inplace=True)

replaceColumns(df.columns)

In [79]:
df.head()

,id,Idade,Faixa idade,Genero,Cor/raca/etnia,PCD,experiencia_profissional_prejudicada,Não acredito que minha experiência profissional seja afetada,Experiencia prejudicada devido a minha Cor Raça Etnia,Experiencia prejudicada devido a minha identidade de gênero,...,Entrando em contato com os times de negócio para definição do problema,Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).,Colocando modelos em produção,Cuidando da manutenção de modelos de Machine Learning já em produção,Realizando construções de dashboards em ferramentas de BI como PowerBI,Utilizando ferramentas avançadas de estatística como SAS,Criando e dando manutenção em ETLs,Criando e gerenciando soluções de Feature Store e cultura de MLOps.,Criando e mantendo a infra que meus modelos e soluções rodam (clusters,Treinando e aplicando LLM's para solucionar problemas de negócio.
0,001b2d1qtli8t9z7oqgdhj001b2d4i0g,31,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0026aa3fwd78u0026asg7456tfkjg2cs,30,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00r21rb9pusd1b0v7ew00r21rw3dy69w,37,35-39,Feminino,Amarela,Não,"Sim, acredito que a minha a experiência profis...",0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00urm3jf2cek12w6ygue00urm3jzd17j,22,22-24,Masculino,Preta,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00v0az4g792svil00vn6y1kfm9hq8vy9,34,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
# Criando um segundo DataFrame somente com as colunas Faixa idade e Genero para agrupar e verificar a quantidade de registros que temos referente ao cruzamento dessas dias dimensões.

df2 = df[['Faixa idade','Genero']]
df2.groupby(['Faixa idade','Genero']).size()

Faixa idade  Genero
17-21        Feminino                  42
             Masculino                135
             Outro                      1
22-24        Feminino                  94
             Masculino                397
             Outro                      1
             Prefiro não informar       1
25-29        Feminino                 414
             Masculino               1233
             Outro                      5
             Prefiro não informar       2
30-34        Feminino                 356
             Masculino               1016
             Outro                      2
             Prefiro não informar       3
35-39        Feminino                 201
             Masculino                581
             Prefiro não informar       8
40-44        Feminino                  98
             Masculino                331
45-49        Feminino                  48
             Masculino                140
             Prefiro não informar       1
50-54        Feminino                  27
             Masculino                 83
             Prefiro não informar       1
55+          Feminino                  13
             Masculino                 59
dtype: int64